name: TypeGraphQL vNext monorepo

on:
  push:
    branches:
      - vNext

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.3, 10.x, 11.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup monorepo
        run: |
          npm install
          npm run bootstrap

      - name: Check codebase
        run: |
          npm run format:check
          npm run lint:check

      - name: Build packages
        run: npm run build

      - name: Run tests
        run: npm run test:ci
        env:
          CI: true
